Music_21:
    db 0
    db 1
    db 0
    db 201
    dw Music_21_Channel_0
    dw Music_21_Channel_1
    dw Music_21_Channel_2
    dw Music_21_Channel_3
    dw Music_21_Channel_4
    dw Music_21_Channel_5
    dw Music_21_Channel_6
    dw Music_21_Channel_7
    dw Music_21_Channel_8
    dw Music_21_Channel_9
Music_21_Channel_0:
      stereo 0c0h
      inst 38
      vol 12
      setRelease 1
      vibrato 05ch
            noteL A4, 48
            note A4
            note D5
            note D5
            note Cs5
            note Cs5
            note Gs4
            note Gs4
      sustain
            noteL B4, 24
    mainLoopStart
      inst 38
      vol 12
      shifting 0
      setRelease 1
            waitL 72
            noteL A4, 96
            note D4
            note G4
            note Fs4
            note Fs4
            note As4
            note G4
            note A4
            note A4
            note As4
            note G4
            note Fs4
            note Fs4
            note G4
            note G4
            note D4
            note As4
            note A4
            note D5
            note Cs5
            note Gs4
      sustain
            noteL B4, 24
    mainLoopEnd
Music_21_Channel_1:
      stereo 0c0h
      inst 38
      vol 9
            waitL 24
      setRelease 1
      vibrato 05ch
            noteL A4, 48
            note A4
            note D5
            note D5
            note Cs5
            note Cs5
            note Gs4
            note Gs4
    mainLoopStart
      inst 38
      vol 9
      shifting 0
      setRelease 1
            noteL B4, 96
            note A4
            note D4
            note G4
            note Fs4
            note Fs4
            note As4
            note G4
            note A4
            note A4
            note As4
            note G4
            note Fs4
            note Fs4
            note G4
            note G4
            note D4
            note As4
            note A4
            note D5
            note Cs5
            note Gs4
    mainLoopEnd
Music_21_Channel_2:
      stereo 0c0h
      inst 38
      vol 12
      setRelease 1
      vibrato 05ch
            noteL Fs4, 48
            note Fs4
            note As4
            note As4
            note A4
            note A4
            note D4
            note D4
      sustain
            noteL F4, 24
    mainLoopStart
      inst 38
      vol 12
      shifting 0
      setRelease 1
            waitL 72
            noteL Fs4, 96
            note As3
            note E4
            note D4
            note D4
            note G4
            note D4
            note Fs4
            note Fs4
            note G4
            note As3
            note D4
            note D4
            note D4
            note D4
            note As3
            note G4
            note Fs4
            note As4
            note A4
            note D4
      sustain
            noteL F4, 24
    mainLoopEnd
Music_21_Channel_3:
      stereo 080h
            waitL 2
      inst 2
      vol 13
      vibrato 00h
            noteL A7, 12
            note Fs7
            note E7
            note D7
            note A6
            note Fs6
            note E6
            note D6
            note As7
            note G7
            note E7
            note D7
            note As6
            note G6
            note E6
            note D6
            note A7
            note E7
            note D7
            note Cs7
            note A6
            note E6
            note D6
            note Cs6
            note B5
            note Gs5
            note D5
            note B4
            note D5
            note E5
            note Gs5
            note B5
            note D6
      sustain
            noteL B5, 10
    mainLoopStart
      inst 2
      vol 13
      shifting 0
      stereo 080h
            waitL 2
            noteL Gs5, 12
            note F5
            note D5
            note B4
            note Gs4
            note F4
            note D6
            note Cs6
            note A6
            note Fs6
            note D6
            note Cs6
            note A5
            note Fs5
            note D7
            note As6
            note G6
            note F6
            note E6
            note D6
            note As5
            note G5
            note D5
            note E5
            note G5
            note As5
            note D6
            note E6
            note G6
            note As6
            note A6
            note Fs6
            note B6
            note A6
            note D7
            note Cs7
            note E7
            note D7
            note G7
            note Fs7
            note B7
            note A7
            note G7
            note Fs7
            note E7
            note D7
            note Cs7
            note As6
            note G6
            note E6
            note Cs6
            note As5
            note G5
            note E5
            note D5
            note E5
            note G5
            note As5
            note D6
            note E6
            note G6
            note As6
            note A6
            note Fs6
            note B6
            note A6
            note D7
            note Cs7
            note E7
            note D7
            note Fs7
            note D7
            note Cs7
            note A6
            note Fs6
            note D6
            note Cs6
            note A5
            note D5
            note E5
            note G5
            note As5
            note D6
            note E6
            note G6
            note As6
            note D6
            note Cs6
            note E6
            note D6
            note F6
            note E6
            note G6
            note F6
            note A6
            note Fs6
            note D6
            note Cs6
            note A5
            note Fs5
            note D5
            note Cs5
            note A4
            note Fs4
            note D4
            note Cs4
            note E4
            note D4
            note Fs4
            note E4
            note G4
            note As4
            note D5
            note E5
            note G5
            note Fs5
            note E5
            note D5
            note G5
            note As5
            note D6
            note E6
            note G6
            note Fs6
            note E6
            note D6
            note As6
            note G6
            note D6
            note G6
            note D6
            note As5
            note G5
            note D5
            note As4
            note D5
            note G5
            note As5
            note G5
            note As5
            note D6
            note Fs6
            note E6
            note D6
            note A5
            note Fs5
            note E5
            note D5
            note A4
            note Fs4
            note E6
            note D6
            note As5
            note G5
            note E5
            note D5
            note As4
            note G4
            note Cs6
            note B5
            note A5
            note E5
            note D5
            note Cs5
            note A4
            note E4
            note D4
            note E4
            note Gs4
            note B4
            note D5
            note E5
            note Gs5
            note B5
            note D6
      sustain
            noteL B5, 10
    mainLoopEnd
Music_21_Channel_4:
      stereo 040h
            waitL 2
      inst 2
      vol 12
      vibrato 00h
            noteL Fs7, 12
            note D7
            note A6
            note Fs6
            note E6
            note D6
            note A5
            note Fs5
            note G7
            note E7
            note As6
            note G6
            note E6
            note D6
            note As5
      setRelease 12
            noteL G5, 24
            noteL A7, 12
            note E7
            note D7
            note Cs7
            note A6
            note E6
            note D6
            note Cs6
            note B5
            note Gs5
            note D5
            note B4
            note D5
            note E5
            note Gs5
            note B5
      sustain
            noteL D6, 10
    mainLoopStart
      inst 2
      vol 12
      shifting 0
      stereo 040h
            waitL 2
            noteL B5, 12
            note Gs5
            note F5
            note D5
            note B4
            note Gs4
            note F4
            note D6
            note Cs6
            note A6
            note Fs6
            note D6
            note Cs6
            note A5
            note Fs5
            note D7
            note As6
            note G6
            note F6
            note E6
            note D6
            note As5
            note G5
            note D5
            note E5
            note G5
            note As5
            note D6
            note E6
            note G6
            note As6
            note A6
            note Fs6
            note B6
            note A6
            note D7
            note Cs7
            note E7
            note D7
            note G7
            note Fs7
            note B7
            note A7
            note G7
            note Fs7
            note E7
            note D7
            note Cs7
            note As6
            note G6
            note E6
            note Cs6
            note As5
            note G5
            note E5
            note D5
            note E5
            note G5
            note As5
            note D6
            note E6
            note G6
            note As6
            note A6
            note Fs6
            note B6
            note A6
            note D7
            note Cs7
            note E7
            note D7
            note Fs7
            note D7
            note Cs7
            note A6
            note Fs6
            note D6
            note Cs6
            note A5
            note D5
            note E5
            note G5
            note As5
            note D6
            note E6
            note G6
            note As6
            note D6
            note Cs6
            note E6
            note D6
            note F6
            note E6
            note G6
            note F6
            note A6
            note Fs6
            note D6
            note Cs6
            note A5
            note Fs5
            note D5
            note Cs5
            note A4
            note Fs4
            note D4
            note Cs4
            note E4
            note D4
            note Fs4
            note E4
            note G4
            note As4
            note D5
            note E5
            note G5
            note Fs5
            note E5
            note D5
            note G5
            note As5
            note D6
            note E6
            note G6
            note Fs6
            note E6
            note D6
            note As6
            note G6
            note D6
            note G6
            note D6
            note As5
            note G5
            note D5
            note As4
            note D5
            note G5
            note As5
            note G5
            note As5
            note D6
            note Fs6
            note E6
            note D6
            note A5
            note Fs5
            note E5
            note D5
            note A4
            note Fs4
            note E6
            note D6
            note As5
            note G5
            note E5
            note D5
            note As4
            note G4
            note Cs6
            note B5
            note A5
            note E5
            note D5
            note Cs5
            note A4
            note E4
            note D4
            note E4
            note Gs4
            note B4
            note D5
            note E5
            note Gs5
            note B5
      sustain
            noteL D6, 10
    mainLoopEnd
Music_21_Channel_5:
    channel_end
Music_21_Channel_6:
            waitL 2
      psgInst 00h
            waitL 18
      psgInst 09h
      setRelease 12
      vibrato 00h
            psgNoteL A5, 12
            psgNote Fs5
            psgNote E5
            psgNote D5
            psgNote A4
            psgNote Fs4
            psgNote E4
            psgNote D4
            psgNote As5
            psgNote G5
            psgNote E5
            psgNote D5
            psgNote As4
            psgNote G4
            psgNote E4
            psgNote D4
            psgNote A5
            psgNote E5
            psgNote D5
            psgNote Cs5
            psgNote A4
            psgNote E4
            psgNote D4
            psgNote Cs4
            psgNote B3
            psgNote Gs3
            psgNote D3
            psgNote B2
            psgNote D3
            psgNote E3
            psgNote Gs3
            psgNote B3
      sustain
            psgNoteL D4, 4
    mainLoopStart
            waitL 8
      setRelease 12
            psgNoteL B3, 12
            psgNote Gs3
            psgNote F3
            psgNote D3
            psgNote B2
            psgNote Gs2
            psgNote F2
            psgNote D4
            psgNote Cs4
            psgNote A4
            psgNote Fs4
            psgNote D4
            psgNote Cs4
            psgNote A3
            psgNote Fs3
            psgNote D5
            psgNote As4
            psgNote G4
            psgNote F4
            psgNote E4
            psgNote D4
            psgNote As3
            psgNote G3
            psgNote D3
            psgNote E3
            psgNote G3
            psgNote As3
            psgNote D4
            psgNote E4
            psgNote G4
            psgNote As4
            psgNote A4
            psgNote Fs4
            psgNote B4
            psgNote A4
            psgNote D5
            psgNote Cs5
            psgNote E5
            psgNote D5
            psgNote G5
            psgNote Fs5
            psgNote B5
            psgNote A5
            psgNote G5
            psgNote Fs5
            psgNote E5
            psgNote D5
            psgNote Cs5
            psgNote As4
            psgNote G4
            psgNote E4
            psgNote Cs4
            psgNote As3
            psgNote G3
            psgNote E3
            psgNote D3
            psgNote E3
            psgNote G3
            psgNote As3
            psgNote D4
            psgNote E4
            psgNote G4
            psgNote As4
            psgNote A4
            psgNote Fs4
            psgNote B4
            psgNote A4
            psgNote D5
            psgNote Cs5
            psgNote E5
            psgNote D5
            psgNote Fs5
            psgNote D5
            psgNote Cs5
            psgNote A4
            psgNote Fs4
            psgNote D4
            psgNote Cs4
            psgNote A3
            psgNote D3
            psgNote E3
            psgNote G3
            psgNote As3
            psgNote D4
            psgNote E4
            psgNote G4
            psgNote As4
            psgNote D4
            psgNote Cs4
            psgNote E4
            psgNote D4
            psgNote F4
            psgNote E4
            psgNote G4
            psgNote F4
            psgNote A4
            psgNote Fs4
            psgNote D4
            psgNote Cs4
            psgNote A3
            psgNote Fs3
            psgNote D3
            psgNote Cs3
            psgNote A2
            psgNote Fs2
            psgNote D2
            psgNote Cs2
            psgNote E2
            psgNote D2
            psgNote Fs2
            psgNote E2
            psgNote G2
            psgNote As2
            psgNote D3
            psgNote E3
            psgNote G3
            psgNote Fs3
            psgNote E3
            psgNote D3
            psgNote G3
            psgNote As3
            psgNote D4
            psgNote E4
            psgNote G4
            psgNote Fs4
            psgNote E4
            psgNote D4
            psgNote As4
            psgNote G4
            psgNote D4
            psgNote G4
            psgNote D4
            psgNote As3
            psgNote G3
            psgNote D3
            psgNote As2
            psgNote D3
            psgNote G3
            psgNote As3
            psgNote G3
            psgNote As3
            psgNote D4
            psgNote Fs4
            psgNote E4
            psgNote D4
            psgNote A3
            psgNote Fs3
            psgNote E3
            psgNote D3
            psgNote A2
            psgNote Fs2
            psgNote E4
            psgNote D4
            psgNote As3
            psgNote G3
            psgNote E3
            psgNote D3
            psgNote As2
            psgNote G2
            psgNote Cs4
            psgNote B3
            psgNote A3
            psgNote E3
            psgNote D3
            psgNote Cs3
            psgNote A2
            psgNote E2
            psgNote D2
            psgNote E2
            psgNote Gs2
            psgNote B2
            psgNote D3
            psgNote E3
            psgNote Gs3
            psgNote B3
      sustain
            psgNoteL D4, 4
    mainLoopEnd
Music_21_Channel_7:
    channel_end
Music_21_Channel_8:
    channel_end
Music_21_Channel_9:
    channel_end