Music_04:
    db 0
    db 0
    db 0
    db 198
    dw Music_04_Channel_0
    dw Music_04_Channel_1
    dw Music_04_Channel_2
    dw Music_04_Channel_3
    dw Music_04_Channel_4
    dw Music_04_Channel_5
    dw Music_04_Channel_6
    dw Music_04_Channel_7
    dw Music_04_Channel_5
    dw Music_04_Channel_5
Music_04_Channel_0:
    mainLoopStart
      inst 23
      vol 9
      setRelease 0
      vibrato 02ch
            noteL C5, 144
            note As4
            note C5
            note Cs5
            note D5
            note Ds5
            note D5
            noteL Ds5, 72
            note F5
            noteL E5, 144
            note Cs5
            noteL C5, 72
            note C5
            noteL Cs5, 144
            note D5
            note Ds5
            note D5
            note Ds5
            noteL Cs5, 72
            note Cs4
            note E4
            noteL E5, 48
            noteL Ds5, 12
            note D5
            noteL Cs5, 72
            note Cs4
            noteL E4, 144
            note F4
            note Fs4
            note G4
            noteL Gs4, 108
            noteL As4, 36
    mainLoopEnd
Music_04_Channel_1:
    mainLoopStart
      inst 23
      vol 9
      setRelease 0
      vibrato 02ch
            noteL G4, 144
            note Fs4
            note G4
            note Fs4
            note A4
            note Gs4
            note A4
            noteL Gs4, 72
            note As4
            noteL C5, 144
            note As4
            noteL G4, 72
            note G4
            noteL As4, 144
            note A4
            note Gs4
            note A4
            noteL Gs4, 72
            noteL As4, 36
            note Gs4
            noteL Gs4, 72
            note Gs3
            note B3
            noteL B4, 48
            noteL As4, 12
            note A4
            noteL Gs4, 72
            note Gs3
            noteL B3, 144
            note B3
            note Cs4
            note Cs4
            noteL Ds4, 72
            note Gs4
    mainLoopEnd
Music_04_Channel_2:
    mainLoopStart
      inst 22
      vol 8
      setRelease 1
      vibrato 02ch
      stereo 040h
      shifting 64
            waitL 9
            noteL E6, 12
            note G5
            note C6
            note E6
            note C6
            note G5
            note G6
            note G5
            note C6
            note E6
            note C6
            note G5
            note Fs6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note As6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note E6
            note G5
            note C6
            note E6
            note C6
            note G5
            note G6
            note G5
            note C6
            note E6
            note C6
            note G5
            note Fs6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note As6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note Fs6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note A6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Gs6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Fs6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note A6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note F6
            note Gs5
            note C6
            note F6
            note C6
            note Gs5
            note E6
            note G5
            note C6
            note E6
            note C6
            note G5
            note G6
            note G5
            note C6
            note E6
            note C6
            note G5
            note Fs6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note As6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note E6
            note G5
            note C6
            note E6
            note C6
            note G5
            note G6
            note G5
            note C6
            note E6
            note C6
            note G5
            note Fs6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note As6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note Fs6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note A6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Gs6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Fs6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note A6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Ds6
            note Gs5
            note C6
            note Gs6
            note C6
            note Gs5
            note F6
            note Gs5
            note Cs6
            note F6
            note Cs6
            note Gs5
            note Gs6
            note Gs5
            note Cs6
            note F6
            note Cs6
            note Gs5
            note E6
            note Gs5
            note B5
            note E6
            note B5
            note Gs5
            note Gs6
            note Gs5
            note B5
            note E6
            note B5
            note Gs5
            note F6
            note Gs5
            note Cs6
            note F6
            note Cs6
            note Gs5
            note Gs6
            note Gs5
            note Cs6
            note F6
            note Cs6
            note Gs5
            note E6
            note Gs5
            note B5
            note E6
            note B5
            note Gs5
            note Gs6
            note Gs5
            note B5
            note E6
            note B5
            note Gs5
            note D6
            note Gs5
            note B5
            note D6
            note B5
            note Gs5
            note F6
            note Gs5
            note B5
            note D6
            note B5
            note Gs5
            note Cs6
            note Fs5
            note As5
            note Cs6
            note As5
            note Fs5
            note Fs6
            note Fs5
            note As5
            note Cs6
            note As5
            note Fs5
            note E6
            note As5
            note Cs6
            note E6
            note Cs6
            note As5
            note G6
            note As5
            note Cs6
            note E6
            note Cs6
            note As5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            noteL Gs5, 3
            noteL C6, 72
    mainLoopEnd
Music_04_Channel_3:
    mainLoopStart
      inst 22
      vol 8
      setRelease 1
      vibrato 02ch
      stereo 080h
      shifting 32
            waitL 4
            noteL E6, 12
            note G5
            note C6
            note E6
            note C6
            note G5
            note G6
            note G5
            note C6
            note E6
            note C6
            note G5
            note Fs6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note As6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note E6
            note G5
            note C6
            note E6
            note C6
            note G5
            note G6
            note G5
            note C6
            note E6
            note C6
            note G5
            note Fs6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note As6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note Fs6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note A6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Gs6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Fs6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note A6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note F6
            note Gs5
            note C6
            note F6
            note C6
            note Gs5
            note E6
            note G5
            note C6
            note E6
            note C6
            note G5
            note G6
            note G5
            note C6
            note E6
            note C6
            note G5
            note Fs6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note As6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note E6
            note G5
            note C6
            note E6
            note C6
            note G5
            note G6
            note G5
            note C6
            note E6
            note C6
            note G5
            note Fs6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note As6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note Fs6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note A6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Gs6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Fs6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note A6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Ds6
            note Gs5
            note C6
            note Gs6
            note C6
            note Gs5
            note F6
            note Gs5
            note Cs6
            note F6
            note Cs6
            note Gs5
            note Gs6
            note Gs5
            note Cs6
            note F6
            note Cs6
            note Gs5
            note E6
            note Gs5
            note B5
            note E6
            note B5
            note Gs5
            note Gs6
            note Gs5
            note B5
            note E6
            note B5
            note Gs5
            note F6
            note Gs5
            note Cs6
            note F6
            note Cs6
            note Gs5
            note Gs6
            note Gs5
            note Cs6
            note F6
            note Cs6
            note Gs5
            note E6
            note Gs5
            note B5
            note E6
            note B5
            note Gs5
            note Gs6
            note Gs5
            note B5
            note E6
            note B5
            note Gs5
            note D6
            note Gs5
            note B5
            note D6
            note B5
            note Gs5
            note F6
            note Gs5
            note B5
            note D6
            note B5
            note Gs5
            note Cs6
            note Fs5
            note As5
            note Cs6
            note As5
            note Fs5
            note Fs6
            note Fs5
            note As5
            note Cs6
            note As5
            note Fs5
            note E6
            note As5
            note Cs6
            note E6
            note Cs6
            note As5
            note G6
            note As5
            note Cs6
            note E6
            note Cs6
            note As5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            noteL Gs5, 8
            noteL Ds6, 72
    mainLoopEnd
Music_04_Channel_4:
    mainLoopStart
      inst 22
      vol 9
      setRelease 1
      vibrato 02ch
            noteL E6, 12
            note G5
            note C6
            note E6
            note C6
            note G5
            note G6
            note G5
            note C6
            note E6
            note C6
            note G5
            note Fs6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note As6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note E6
            note G5
            note C6
            note E6
            note C6
            note G5
            note G6
            note G5
            note C6
            note E6
            note C6
            note G5
            note Fs6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note As6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note Fs6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note A6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Gs6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Fs6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note A6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note F6
            note Gs5
            note C6
            note F6
            note C6
            note Gs5
            note E6
            note G5
            note C6
            note E6
            note C6
            note G5
            note G6
            note G5
            note C6
            note E6
            note C6
            note G5
            note Fs6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note As6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note E6
            note G5
            note C6
            note E6
            note C6
            note G5
            note G6
            note G5
            note C6
            note E6
            note C6
            note G5
            note Fs6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note As6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note Fs6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note A6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Gs6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Fs6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note A6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Ds6
            note Gs5
            note C6
            note Gs6
            note C6
            note Gs5
            note F6
            note Gs5
            note Cs6
            note F6
            note Cs6
            note Gs5
            note Gs6
            note Gs5
            note Cs6
            note F6
            note Cs6
            note Gs5
            note E6
            note Gs5
            note B5
            note E6
            note B5
            note Gs5
            note Gs6
            note Gs5
            note B5
            note E6
            note B5
            note Gs5
            note F6
            note Gs5
            note Cs6
            note F6
            note Cs6
            note Gs5
            note Gs6
            note Gs5
            note Cs6
            note F6
            note Cs6
            note Gs5
            note E6
            note Gs5
            note B5
            note E6
            note B5
            note Gs5
            note Gs6
            note Gs5
            note B5
            note E6
            note B5
            note Gs5
            note D6
            note Gs5
            note B5
            note D6
            note B5
            note Gs5
            note F6
            note Gs5
            note B5
            note D6
            note B5
            note Gs5
            note Cs6
            note Fs5
            note As5
            note Cs6
            note As5
            note Fs5
            note Fs6
            note Fs5
            note As5
            note Cs6
            note As5
            note Fs5
            note E6
            note As5
            note Cs6
            note E6
            note Cs6
            note As5
            note G6
            note As5
            note Cs6
            note E6
            note Cs6
            note As5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            noteL Gs6, 72
    mainLoopEnd
Music_04_Channel_5:
    channel_end
Music_04_Channel_6:
    mainLoopStart
      psgInst 098h
      setRelease 0
      vibrato 02ch
            psgNoteL C2, 144
            psgNote As1
            psgNote C2
            psgNote Cs2
            psgNote D2
            psgNote Ds2
            psgNote D2
            psgNoteL Ds2, 72
            psgNote F2
            psgNoteL E2, 144
            psgNote Cs2
            psgNoteL C2, 72
            psgNote C2
            psgNoteL Cs2, 144
            psgNote D2
            psgNote Ds2
            psgNote D2
            psgNote Ds2
            psgNoteL Cs2, 72
            psgNote Cs2
            psgNote E2
            psgNoteL E2, 48
            psgNoteL Ds2, 12
            psgNote D2
            psgNoteL Cs2, 72
            psgNote Cs2
            psgNoteL E2, 144
            psgNote F2
            psgNote Fs2
            psgNote G2
            psgNoteL Gs2, 108
            psgNoteL As1, 36
    mainLoopEnd
Music_04_Channel_7:
    mainLoopStart
      psgInst 098h
      setRelease 0
      vibrato 02ch
            psgNoteL G2, 144
            psgNote Fs2
            psgNote G2
            psgNote Fs2
            psgNote A2
            psgNote Gs2
            psgNote A2
            psgNoteL Gs2, 72
            psgNote As2
            psgNoteL C3, 144
            psgNote As2
            psgNoteL G2, 72
            psgNote G2
            psgNoteL As2, 144
            psgNote A2
            psgNote Gs2
            psgNote A2
            psgNoteL Gs2, 72
            psgNoteL As2, 36
            psgNote Gs2
            psgNoteL Gs2, 72
            psgNote Gs1
            psgNote B1
            psgNoteL B2, 48
            psgNoteL As2, 12
            psgNote A2
            psgNoteL Gs2, 72
            psgNote Gs2
            psgNoteL B1, 144
            psgNote B1
            psgNote Cs2
            psgNote Cs2
            psgNoteL Ds2, 72
            psgNote Gs2
    mainLoopEnd