Music_14:
    db 0
    db 1
    db 0
    db 197
    dw Music_14_Channel_0
    dw Music_14_Channel_1
    dw Music_14_Channel_2
    dw Music_14_Channel_3
    dw Music_14_Channel_4
    dw Music_14_Channel_5
    dw Music_14_Channel_6
    dw Music_14_Channel_7
    dw Music_14_Channel_8
    dw Music_14_Channel_8
Music_14_Channel_0:
    mainLoopStart
      inst 61
      vol 13
      setRelease 2
      vibrato 02ch
      stereo 080h
            noteL C6, 12
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
    mainLoopEnd
Music_14_Channel_1:
    mainLoopStart
      inst 19
      vol 13
      setRelease 1
      vibrato 024h
            waitL 96
            wait
            wait
            wait
      sustain
            noteL C7, 192
            note C7
      setRelease 1
            note C7
      inst 43
      vol 12
            noteL C6, 48
            note G5
            note C5
            note C4
      inst 42
      vol 15
            note C3
      inst 19
      vol 12
            note Ds4
            note Cs4
            wait
      inst 42
      vol 15
            note C3
      inst 19
      vol 12
            note Ds4
            note E4
            wait
      inst 42
      vol 15
            note C3
      inst 19
      vol 12
            note Ds4
            note Cs4
            wait
      inst 42
      vol 15
            note C3
      inst 19
      vol 12
            note Ds4
            note E4
            wait
      inst 42
      vol 15
            note C3
      inst 19
      vol 12
            note Ds4
            note Cs4
      inst 43
      vol 12
            note G6
      inst 42
      vol 15
            note C3
      inst 19
      vol 12
            note Ds4
            note E4
      inst 43
      vol 12
            note Fs6
      inst 42
      vol 15
            note C3
      inst 19
      vol 12
            note Ds4
            note Cs4
      inst 43
      vol 12
            note G6
      inst 42
      vol 15
            note C3
      inst 19
      vol 12
            note Ds4
            note E4
      inst 43
      vol 12
            note Fs6
      inst 42
      vol 15
            note C3
      inst 19
      vol 12
            note Ds4
            note Cs4
      inst 43
      vol 12
            note G6
      inst 42
      vol 15
            note C3
      inst 19
      vol 12
            note Ds4
            note E4
      inst 43
      vol 12
      vibrato 02ch
            note F6
    mainLoopEnd
Music_14_Channel_2:
    mainLoopStart
      inst 19
      vol 13
      setRelease 1
      vibrato 02ch
            waitL 96
            wait
            wait
            wait
      sustain
            noteL Cs7, 192
            note Cs7
      setRelease 1
            note Cs7
      inst 43
      vol 12
      setRelease 2
            noteL Cs6, 48
            note Gs5
            note Cs5
            waitL 60
      inst 19
      vol 9
      shifting 32
            noteL C3, 48
            note Ds4
            note Cs4
            wait
            note C3
            note Ds4
            note E4
            wait
            note C3
            note Ds4
            note Cs4
            wait
            note C3
            note Ds4
            note E4
            wait
            note C3
            note Ds4
            noteL Cs4, 36
      inst 43
      vol 12
      shifting 0
            noteL Gs7, 48
            waitL 12
      inst 19
      vol 9
      shifting 32
            noteL C3, 48
            note Ds4
            noteL E4, 36
      inst 43
      vol 12
      shifting 0
            noteL G7, 48
            waitL 12
      inst 19
      vol 9
      shifting 32
            noteL C3, 48
            note Ds4
            noteL Cs4, 36
      inst 43
      vol 12
      shifting 0
            noteL Gs7, 48
            waitL 12
      inst 19
      vol 9
      shifting 32
            noteL C3, 48
            note Ds4
            noteL E4, 36
      inst 43
      vol 12
      shifting 0
            noteL G7, 48
            waitL 12
      inst 19
      vol 9
      shifting 32
            noteL C3, 48
            note Ds4
            noteL Cs4, 36
      inst 43
      vol 12
      shifting 0
            noteL Gs7, 48
            waitL 12
      inst 19
      vol 9
      shifting 32
            noteL C3, 48
            note Ds4
            noteL E4, 36
      inst 43
      vol 12
      shifting 32
            noteL Fs7, 48
    mainLoopEnd
Music_14_Channel_3:
      vol 0
            waitL 3
    mainLoopStart
      inst 61
      vol 11
      setRelease 1
      vibrato 02ch
      shifting 16
      stereo 040h
            noteL C6, 12
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
    mainLoopEnd
Music_14_Channel_4:
      vol 0
            waitL 24
    mainLoopStart
      inst 43
      vol 5
      setRelease 1
      vibrato 02ch
      shifting 32
            waitL 96
            wait
            wait
            wait
      sustain
            noteL C7, 192
      shifting 48
            note C7
      shifting 64
      setRelease 2
            note C7
      shifting 32
            noteL C6, 48
            note G5
            note C5
            note C4
            note C3
            note Ds4
            note Cs4
            wait
            note C3
            note Ds4
            note E4
            wait
            note C3
            note Ds4
            note Cs4
            wait
            note C3
            note Ds4
            note E4
            wait
            note C3
            note Ds4
            note Cs4
            note G6
            note C3
            note Ds4
            note E4
            note Fs6
            note C3
            note Ds4
            note Cs4
            note G6
            note C3
            note Ds4
            note E4
            note Fs6
            note C3
            note Ds4
            note Cs4
            note G6
            note C3
            note Ds4
            note E4
            note F6
    mainLoopEnd
Music_14_Channel_5:
    mainLoopStart
      inst 62
      vol 15
      setRelease 1
      vibrato 02ch
            waitL 24
            noteL D2, 22
      vol 10
            noteL C2, 18
            waitL 32
    mainLoopEnd
Music_14_Channel_6:
    mainLoopStart
      psgInst 099h
      setRelease 1
      vibrato 04fh
            psgNoteL C4, 0
      setRelease 129
            psgNoteL D4, 192
            psgNote Cs4
            psgNote D4
            psgNote Cs4
            psgNote Ds4
            psgNote D4
            psgNote Cs4
            psgNote E4
            psgNote Ds4
            psgNote D4
            psgNote Cs4
            psgNote E4
            psgNote F4
            psgNote E4
            psgNote D4
            psgNote Ds4
      setRelease 255
    mainLoopEnd
Music_14_Channel_7:
    mainLoopStart
      psgInst 099h
      setRelease 1
      vibrato 04fh
            psgNoteL Fs4, 0
      setRelease 129
            psgNoteL Gs4, 192
            psgNote G4
            psgNote Gs4
            psgNote G4
            psgNote A4
            psgNote Gs4
            psgNote G4
            psgNote As4
            psgNote A4
            psgNote Gs4
            psgNote G4
            psgNote As4
            psgNote B4
            psgNote As4
            psgNote Gs4
            psgNote A4
      setRelease 255
    mainLoopEnd
Music_14_Channel_8:
    channel_end