Music_04:
    db 0
    db 1
    db 0
    db 201
    dw Music_04_Channel_0
    dw Music_04_Channel_1
    dw Music_04_Channel_2
    dw Music_04_Channel_3
    dw Music_04_Channel_4
    dw Music_04_Channel_5
    dw Music_04_Channel_6
    dw Music_04_Channel_7
    dw Music_04_Channel_8
    dw Music_04_Channel_9
Music_04_Channel_0:
      stereo 0c0h
    mainLoopStart
      inst 0
      vol 0
      shifting 0
      inst 23
      vol 9
            noteL C5, 144
      vibrato 05ch
            note As4
            note C5
            note Cs5
            note D5
            note Ds5
            note D5
            noteL Ds5, 72
            note F5
            noteL E5, 144
            note Cs5
            noteL C5, 72
            note C5
            noteL Cs5, 144
            note D5
            note Ds5
            note D5
            note Ds5
            noteL Cs5, 72
            note Cs4
            note E4
            noteL E5, 48
            noteL Ds5, 12
            note D5
            noteL Cs5, 72
            note Cs4
            noteL E4, 144
            note F4
            note Fs4
            note G4
            noteL Gs4, 108
      sustain
            noteL As4, 36
    mainLoopEnd
Music_04_Channel_1:
      stereo 0c0h
    mainLoopStart
      inst 0
      vol 0
      shifting 0
      inst 23
      vol 9
            noteL G4, 144
      vibrato 05ch
            note Fs4
            note G4
            note Fs4
            note A4
            note Gs4
            note A4
            noteL Gs4, 72
            note As4
            noteL C5, 144
            note As4
            noteL G4, 72
            note G4
            noteL As4, 144
            note A4
            note Gs4
            note A4
            noteL Gs4, 72
            noteL As4, 36
            note Gs4
            noteL Gs4, 72
            note Gs3
            note B3
            noteL B4, 48
            noteL As4, 12
            note A4
            noteL Gs4, 72
            note Gs3
            noteL B3, 144
            note B3
            note Cs4
            note Cs4
            noteL Ds4, 72
      sustain
            note Gs4
    mainLoopEnd
Music_04_Channel_2:
      stereo 0c0h
    mainLoopStart
      inst 0
      vol 0
      shifting 0
      shifting 64
      stereo 040h
      inst 22
      vol 8
            waitL 9
      setRelease 1
      vibrato 05ch
            noteL E6, 12
            note G5
            note C6
            note E6
            note C6
            note G5
            note G6
            note G5
            note C6
            note E6
            note C6
            note G5
            note Fs6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note As6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note E6
            note G5
            note C6
            note E6
            note C6
            note G5
            note G6
            note G5
            note C6
            note E6
            note C6
            note G5
            note Fs6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note As6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note Fs6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note A6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Gs6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Fs6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note A6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note F6
            note Gs5
            note C6
            note F6
            note C6
            note Gs5
            note E6
            note G5
            note C6
            note E6
            note C6
            note G5
            note G6
            note G5
            note C6
            note E6
            note C6
            note G5
            note Fs6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note As6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note E6
            note G5
            note C6
            note E6
            note C6
            note G5
            note G6
            note G5
            note C6
            note E6
            note C6
            note G5
            note Fs6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note As6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note Fs6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note A6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Gs6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Fs6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note A6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Ds6
            note Gs5
            note C6
            note Gs6
            note C6
            note Gs5
            note F6
            note Gs5
            note Cs6
            note F6
            note Cs6
            note Gs5
            note Gs6
            note Gs5
            note Cs6
            note F6
            note Cs6
            note Gs5
            note E6
            note Gs5
            note B5
            note E6
            note B5
            note Gs5
            note Gs6
            note Gs5
            note B5
            note E6
            note B5
            note Gs5
            note F6
            note Gs5
            note Cs6
            note F6
            note Cs6
            note Gs5
            note Gs6
            note Gs5
            note Cs6
            note F6
            note Cs6
            note Gs5
            note E6
            note Gs5
            note B5
            note E6
            note B5
            note Gs5
            note Gs6
            note Gs5
            note B5
            note E6
            note B5
            note Gs5
            note D6
            note Gs5
            note B5
            note D6
            note B5
            note Gs5
            note F6
            note Gs5
            note B5
            note D6
            note B5
            note Gs5
            note Cs6
            note Fs5
            note As5
            note Cs6
            note As5
            note Fs5
            note Fs6
            note Fs5
            note As5
            note Cs6
            note As5
            note Fs5
            note E6
            note As5
            note Cs6
            note E6
            note Cs6
            note As5
            note G6
            note As5
            note Cs6
            note E6
            note Cs6
            note As5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            noteL Gs5, 3
            noteL C6, 72
    mainLoopEnd
Music_04_Channel_3:
      stereo 0c0h
    mainLoopStart
      inst 0
      vol 0
      shifting 0
      shifting 32
      stereo 080h
      inst 22
      vol 8
            waitL 4
      setRelease 1
      vibrato 05ch
            noteL E6, 12
            note G5
            note C6
            note E6
            note C6
            note G5
            note G6
            note G5
            note C6
            note E6
            note C6
            note G5
            note Fs6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note As6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note E6
            note G5
            note C6
            note E6
            note C6
            note G5
            note G6
            note G5
            note C6
            note E6
            note C6
            note G5
            note Fs6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note As6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note Fs6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note A6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Gs6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Fs6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note A6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note F6
            note Gs5
            note C6
            note F6
            note C6
            note Gs5
            note E6
            note G5
            note C6
            note E6
            note C6
            note G5
            note G6
            note G5
            note C6
            note E6
            note C6
            note G5
            note Fs6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note As6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note E6
            note G5
            note C6
            note E6
            note C6
            note G5
            note G6
            note G5
            note C6
            note E6
            note C6
            note G5
            note Fs6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note As6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note Fs6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note A6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Gs6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Fs6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note A6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Ds6
            note Gs5
            note C6
            note Gs6
            note C6
            note Gs5
            note F6
            note Gs5
            note Cs6
            note F6
            note Cs6
            note Gs5
            note Gs6
            note Gs5
            note Cs6
            note F6
            note Cs6
            note Gs5
            note E6
            note Gs5
            note B5
            note E6
            note B5
            note Gs5
            note Gs6
            note Gs5
            note B5
            note E6
            note B5
            note Gs5
            note F6
            note Gs5
            note Cs6
            note F6
            note Cs6
            note Gs5
            note Gs6
            note Gs5
            note Cs6
            note F6
            note Cs6
            note Gs5
            note E6
            note Gs5
            note B5
            note E6
            note B5
            note Gs5
            note Gs6
            note Gs5
            note B5
            note E6
            note B5
            note Gs5
            note D6
            note Gs5
            note B5
            note D6
            note B5
            note Gs5
            note F6
            note Gs5
            note B5
            note D6
            note B5
            note Gs5
            note Cs6
            note Fs5
            note As5
            note Cs6
            note As5
            note Fs5
            note Fs6
            note Fs5
            note As5
            note Cs6
            note As5
            note Fs5
            note E6
            note As5
            note Cs6
            note E6
            note Cs6
            note As5
            note G6
            note As5
            note Cs6
            note E6
            note Cs6
            note As5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            noteL Gs5, 8
            noteL Ds6, 72
    mainLoopEnd
Music_04_Channel_4:
      stereo 0c0h
    mainLoopStart
      inst 0
      vol 0
      shifting 0
      inst 22
      vol 9
      setRelease 1
      vibrato 05ch
            noteL E6, 12
            note G5
            note C6
            note E6
            note C6
            note G5
            note G6
            note G5
            note C6
            note E6
            note C6
            note G5
            note Fs6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note As6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note E6
            note G5
            note C6
            note E6
            note C6
            note G5
            note G6
            note G5
            note C6
            note E6
            note C6
            note G5
            note Fs6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note As6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note Fs6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note A6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Gs6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Fs6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note A6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note F6
            note Gs5
            note C6
            note F6
            note C6
            note Gs5
            note E6
            note G5
            note C6
            note E6
            note C6
            note G5
            note G6
            note G5
            note C6
            note E6
            note C6
            note G5
            note Fs6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note As6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note E6
            note G5
            note C6
            note E6
            note C6
            note G5
            note G6
            note G5
            note C6
            note E6
            note C6
            note G5
            note Fs6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note As6
            note As5
            note Cs6
            note Fs6
            note Cs6
            note As5
            note Fs6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note A6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Gs6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Fs6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note A6
            note A5
            note D6
            note Fs6
            note D6
            note A5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            note Ds6
            note Gs5
            note C6
            note Gs6
            note C6
            note Gs5
            note F6
            note Gs5
            note Cs6
            note F6
            note Cs6
            note Gs5
            note Gs6
            note Gs5
            note Cs6
            note F6
            note Cs6
            note Gs5
            note E6
            note Gs5
            note B5
            note E6
            note B5
            note Gs5
            note Gs6
            note Gs5
            note B5
            note E6
            note B5
            note Gs5
            note F6
            note Gs5
            note Cs6
            note F6
            note Cs6
            note Gs5
            note Gs6
            note Gs5
            note Cs6
            note F6
            note Cs6
            note Gs5
            note E6
            note Gs5
            note B5
            note E6
            note B5
            note Gs5
            note Gs6
            note Gs5
            note B5
            note E6
            note B5
            note Gs5
            note D6
            note Gs5
            note B5
            note D6
            note B5
            note Gs5
            note F6
            note Gs5
            note B5
            note D6
            note B5
            note Gs5
            note Cs6
            note Fs5
            note As5
            note Cs6
            note As5
            note Fs5
            note Fs6
            note Fs5
            note As5
            note Cs6
            note As5
            note Fs5
            note E6
            note As5
            note Cs6
            note E6
            note Cs6
            note As5
            note G6
            note As5
            note Cs6
            note E6
            note Cs6
            note As5
            note Ds6
            note Gs5
            note C6
            note Ds6
            note C6
            note Gs5
            noteL Gs6, 72
    mainLoopEnd
Music_04_Channel_5:
    channel_end
Music_04_Channel_6:
    mainLoopStart
      psgInst 098h
      setRelease 144
            psgNoteL C2, 144
      vibrato 04ch
            psgNote As1
            psgNote C2
            psgNote Cs2
            psgNote D2
            psgNote Ds2
            psgNote D2
      setRelease 72
            psgNoteL Ds2, 72
            psgNote F2
      setRelease 144
            psgNoteL E2, 144
            psgNote Cs2
      setRelease 72
            psgNoteL C2, 72
            psgNote C2
      setRelease 144
            psgNoteL Cs2, 144
            psgNote D2
            psgNote Ds2
            psgNote D2
            psgNote Ds2
      setRelease 72
            psgNoteL Cs2, 72
            psgNote Cs2
            psgNote E2
      setRelease 48
            psgNoteL E2, 48
      setRelease 12
            psgNoteL Ds2, 12
            psgNote D2
      setRelease 72
            psgNoteL Cs2, 72
            psgNote Cs2
      setRelease 144
            psgNoteL E2, 144
            psgNote F2
            psgNote Fs2
            psgNote G2
      setRelease 108
            psgNoteL Gs2, 108
      sustain
            psgNoteL As1, 36
    mainLoopEnd
Music_04_Channel_7:
    mainLoopStart
      psgInst 098h
      setRelease 144
            psgNoteL G2, 144
      vibrato 04ch
            psgNote Fs2
            psgNote G2
            psgNote Fs2
            psgNote A2
            psgNote Gs2
            psgNote A2
      setRelease 72
            psgNoteL Gs2, 72
            psgNote As2
      setRelease 144
            psgNoteL C3, 144
            psgNote As2
      setRelease 72
            psgNoteL G2, 72
            psgNote G2
      setRelease 144
            psgNoteL As2, 144
            psgNote A2
            psgNote Gs2
            psgNote A2
      setRelease 72
            psgNoteL Gs2, 72
      setRelease 36
            psgNoteL As2, 36
            psgNote Gs2
      setRelease 72
            psgNoteL Gs2, 72
            psgNote Gs1
            psgNote B1
      setRelease 48
            psgNoteL B2, 48
      setRelease 12
            psgNoteL As2, 12
            psgNote A2
      setRelease 72
            psgNoteL Gs2, 72
            psgNote Gs2
      setRelease 144
            psgNoteL B1, 144
            psgNote B1
            psgNote Cs2
            psgNote Cs2
      setRelease 72
            psgNoteL Ds2, 72
      sustain
            psgNote Gs2
    mainLoopEnd
Music_04_Channel_8:
    channel_end
Music_04_Channel_9:
    channel_end