Music_08:
    db 0
    db 0
    db 0
    db 195
    dw Music_08_Channel_0
    dw Music_08_Channel_1
    dw Music_08_Channel_2
    dw Music_08_Channel_3
    dw Music_08_Channel_4
    dw Music_08_Channel_5
    dw Music_08_Channel_6
    dw Music_08_Channel_7
    dw Music_08_Channel_8
    dw Music_08_Channel_9
Music_08_Channel_0:
      stereo 0c0h
    mainLoopStart
      inst 0
      vol 0
      shifting 0
      inst 26
      vol 10
      setRelease 1
      vibrato 00h
            noteL B3, 6
            note As3
            note E3
            note D4
            note Cs4
            note B3
            note As3
            note E3
            note D4
            note Cs4
            note E4
            note Ds4
            note B3
            note As3
            note E3
            note D4
            note Cs4
            note B3
            note As3
            note E3
            note D4
            note Cs4
            note E4
            note Ds4
            note F4
            note E4
            note B3
            note F4
            note B3
            note F4
            note E4
            note B3
            note F4
            note B3
            note F4
            note B3
            note F4
            note E4
            note B3
            note F4
            note B3
            note F4
            note E4
            note B3
            note F4
            note B3
            note F4
            note B3
            note B3
            note As3
            note E3
            note D4
            note Cs4
            note B3
            note As3
            note E3
            note D4
            note Cs4
            note E4
            note Ds4
            note B3
            note As3
            note E3
            note D4
            note Cs4
            note B3
            note As3
            note E3
            note D4
            note Cs4
            note E4
            note Ds4
            note F4
            note E4
            note B3
            note F4
            note B3
            note F4
            note E4
            note B3
            note F4
            note B3
            note F4
            note B3
            note F4
            note E4
            note B3
            note F4
            note B3
            note F4
            note E4
            note B3
            note F4
            note B3
            note F4
            note B3
            note F4
            note B3
            note B3
            note E4
            note As3
            note As3
            note Ds4
            note A3
            note A3
            note D4
            note Gs3
            note Gs3
            note Cs4
            note G3
            note G3
            note C4
            note Fs3
            note Fs3
            note B3
            note F3
            note F3
            note As3
            note E3
            note E3
            note F4
            note B3
            note B3
            note E4
            note As3
            note As3
            note Ds4
            note A3
            note A3
            note D4
            note Gs3
            note Gs3
            note Cs4
            note G3
            note G3
            note C4
            note Fs3
            note Fs3
            note B3
            note F3
            note F3
            note As3
            note E3
            note E3
    mainLoopEnd
Music_08_Channel_1:
      stereo 0c0h
    mainLoopStart
      inst 0
      vol 0
      shifting 0
      inst 21
      vol 10
      setRelease 1
      vibrato 00h
            noteL B3, 6
            note As3
            note E3
            note D4
            note Cs4
            note B3
            note As3
            note E3
            note D4
            note Cs4
            note E4
            note Ds4
            note B3
            note As3
            note E3
            note D4
            note Cs4
            note B3
            note As3
            note E3
            note D4
            note Cs4
            note E4
            note Ds4
            note F4
            note E4
            note B3
            note F4
            note B3
            note F4
            note E4
            note B3
            note F4
            note B3
            note F4
            note B3
            note F4
            note E4
            note B3
            note F4
            note B3
            note F4
            note E4
            note B3
            note F4
            note B3
            note F4
            note B3
            note B3
            note As3
            note E3
            note D4
            note Cs4
            note B3
            note As3
            note E3
            note D4
            note Cs4
            note E4
            note Ds4
            note B3
            note As3
            note E3
            note D4
            note Cs4
            note B3
            note As3
            note E3
            note D4
            note Cs4
            note E4
            note Ds4
            note F4
            note E4
            note B3
            note F4
            note B3
            note F4
            note E4
            note B3
            note F4
            note B3
            note F4
            note B3
            note F4
            note E4
            note B3
            note F4
            note B3
            note F4
            note E4
            note B3
            note F4
            note B3
            note F4
            note B3
            note F4
            note B3
            note B3
            note E4
            note As3
            note As3
            note Ds4
            note A3
            note A3
            note D4
            note Gs3
            note Gs3
            note Cs4
            note G3
            note G3
            note C4
            note Fs3
            note Fs3
            note B3
            note F3
            note F3
            note As3
            note E3
            note E3
            note F4
            note B3
            note B3
            note E4
            note As3
            note As3
            note Ds4
            note A3
            note A3
            note D4
            note Gs3
            note Gs3
            note Cs4
            note G3
            note G3
            note C4
            note Fs3
            note Fs3
            note B3
            note F3
            note F3
            note As3
            note E3
            note E3
    mainLoopEnd
Music_08_Channel_2:
      stereo 0c0h
    mainLoopStart
      inst 0
      vol 0
      shifting 0
      inst 17
      vol 10
      setRelease 1
            noteL G5, 72
      vibrato 05ah
            note Fs5
            note F5
            note G5
            note G5
            note Fs5
            note F5
            note G5
      vol 8
            waitL 10
            noteL C5, 6
            note Cs5
            note Fs5
            note G5
            note D5
            note Ds5
            note Gs5
            note A5
            note E5
            note F5
            note As5
            note B5
            note F5
            note Fs5
            note B5
            note C6
            note G5
            note Gs5
            note Cs6
            note D6
            note A5
            note As5
            note Ds6
            noteL E6, 1
            noteL C5, 6
            note Cs5
            note Fs5
            note G5
            note D5
            note Ds5
            note Gs5
            note A5
            note E5
            note F5
            note As5
            note B5
            note F5
            note Fs5
            note B5
            note C6
            note G5
            note Gs5
            note Cs6
            note D6
            note A5
            note As5
            note Ds6
      sustain
            noteL E6, 1
    mainLoopEnd
Music_08_Channel_3:
      stereo 0c0h
    mainLoopStart
      inst 0
      vol 0
      shifting 0
      inst 17
      vol 10
      setRelease 1
            noteL B5, 72
      vibrato 05ah
            note A5
            note A5
            note B5
            note B5
            note A5
            note A5
            note B5
            noteL G5, 6
            note Gs5
            note Cs6
            note D6
            note A5
            note As5
            note Ds6
            note E6
            note B5
            note C6
            note F6
            note Fs6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note E6
            note F6
            note As6
            note B6
            note G5
            note Gs5
            note Cs6
            note D6
            note A5
            note As5
            note Ds6
            note E6
            note B5
            note C6
            note F6
            note Fs6
            note C6
            note Cs6
            note Fs6
            note G6
            note D6
            note Ds6
            note Gs6
            note A6
            note E6
            note F6
            note As6
            note B6
    mainLoopEnd
Music_08_Channel_4:
      stereo 0c0h
    mainLoopStart
      inst 0
      vol 0
      shifting 0
      stereo 040h
      inst 25
      vol 7
      setRelease 1
      vibrato 00h
            noteL B5, 3
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
      stereo 080h
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
      stereo 040h
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
      stereo 080h
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
      stereo 040h
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
      stereo 080h
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
      stereo 040h
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
      stereo 080h
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
      stereo 040h
      inst 6
      vol 7
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
      stereo 080h
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
      stereo 040h
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
      stereo 080h
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
      stereo 040h
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
      stereo 080h
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
      stereo 040h
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
      stereo 080h
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
            note B5
            note E6
            note F6
            note B6
    mainLoopEnd
Music_08_Channel_5:
    mainLoopStart
            sampleL 0, 6
            sample 0
            sample 0
            sampleL 1, 18
            sampleL 0, 6
            sample 0
            sample 1
            sample 0
            sample 0
            sample 1
            sample 0
            sample 0
            sample 2
            sample 2
            sample 3
            sample 3
            sample 4
            sample 4
            sample 1
            sample 1
            sample 1
            sample 1
            sample 1
            sample 0
            sample 0
            sample 1
            sample 0
            sample 1
            sample 0
            sample 0
            sample 1
            sample 0
            sample 1
            sample 0
            sample 1
            sample 0
            sample 0
            sample 1
            sample 0
            sample 1
            sample 0
            sample 0
            sample 1
            sample 0
            sample 1
            sample 0
            sample 0
            sample 0
            sample 0
            sampleL 1, 18
            sampleL 0, 6
            sample 0
            sample 1
            sample 0
            sample 0
            sample 1
            sample 0
            sample 0
            sample 2
            sample 2
            sample 3
            sample 3
            sample 4
            sample 4
            sample 1
            sample 1
            sample 1
            sample 1
            sample 1
            sample 0
            sample 0
            sample 1
            sample 0
            sample 1
            sample 0
            sample 0
            sample 1
            sample 0
            sample 1
            sample 0
            sample 1
            sample 0
            sample 0
            sample 1
            sample 0
            sample 1
            sample 0
            sample 0
            sample 1
            sample 0
            sample 1
            sample 0
            sampleL 1, 3
            sample 1
            sample 1
            sample 1
            sampleL 2, 6
            sample 2
            sample 2
            sample 3
            sample 3
            sample 3
            sample 4
            sample 4
            sample 4
            sample 1
            sampleL 0, 12
            sample 1
            sampleL 0, 6
            sample 0
            sampleL 1, 12
            sampleL 0, 6
            sample 0
            sample 1
            sample 0
            sample 1
            sample 0
            sample 0
            sample 1
            sample 0
            sample 0
            sample 1
            sample 0
            sample 0
            sample 1
            sample 0
            sample 0
            sample 1
            sample 0
            sample 0
            sample 1
            sample 0
            sample 0
            sample 1
            sample 0
            sample 0
            sample 1
            sample 0
            sample 0
    mainLoopEnd
Music_08_Channel_6:
    channel_end
Music_08_Channel_7:
    channel_end
Music_08_Channel_8:
    channel_end
Music_08_Channel_9:
    channel_end