Music_21:
    db 0
    db 0
    db 0
    db 176
    dw Music_21_Channel_0
    dw Music_21_Channel_1
    dw Music_21_Channel_2
    dw Music_21_Channel_3
    dw Music_21_Channel_4
    dw Music_21_Channel_5
    dw Music_21_Channel_6
    dw Music_21_Channel_7
    dw Music_21_Channel_8
    dw Music_21_Channel_8
Music_21_Channel_0:
      inst 26
      vol 11
      setRelease 1
      vibrato 44
            noteL E5, 24
            note Cs5
            note E5
            note Cs5
            note E5
            note Cs5
            note E5
            note Cs5
            note E5
            note Cs5
            note E5
            note Cs5
            note E5
            note Cs5
            note E5
            note Cs5
            noteL E5, 96
    channel_end
Music_21_Channel_1:
      inst 26
      vol 11
      setRelease 1
      vibrato 44
            noteL C5, 24
            note As4
            note C5
            note As4
            note C5
            note As4
            note C5
            note As4
            note C5
            note As4
            note C5
            note As4
            note C5
            note As4
            note C5
            note As4
            noteL C5, 96
    channel_end
Music_21_Channel_2:
      inst 26
      vol 11
      setRelease 1
      vibrato 44
            noteL G4, 4
            note A4
            note G4
            note A4
            note G4
            note A4
            note As4
            note C5
            note As4
            note C5
            note As4
            note C5
            note Cs5
            note Ds5
            note Cs5
            note Ds5
            note Cs5
            note Ds5
            note E5
            note Fs5
            note E5
            note Fs5
            note E5
            note Fs5
            note G5
            note A5
            note G5
            note A5
            note G5
            note A5
            note As5
            note C6
            note As5
            note C6
            note As5
            note C6
            note Cs6
            note Ds6
            note Cs6
            note Ds6
            note Cs6
            note Ds6
            note E6
            note Fs6
            note E6
            note Fs6
            note E6
            note Fs6
            note As5
            note C6
            note As5
            note C6
            note As5
            note C6
            note Cs6
            note Ds6
            note Cs6
            note Ds6
            note Cs6
            note Ds6
            note E6
            note Fs6
            note E6
            note Fs6
            note E6
            note Fs6
            note G6
            note A6
            note G6
            note A6
            note G6
            note A6
            note As6
            note C7
            note As6
            note C7
            note As6
            note C7
            note Cs7
            note Ds7
            note Cs7
            note Ds7
            note Cs7
            note Ds7
            note E7
            note Fs7
            note E7
            note Fs7
            note E7
            note Fs7
            note G7
            note A7
            note G7
            note A7
            note G7
            note A7
            note As7
            note C8
            note As7
            note C8
            note As7
            note C8
            note As7
            note C8
            note As7
            note C8
            note As7
            note C8
            note As7
            note C8
            note As7
            note C8
            note As7
            note C8
            note As7
            note C8
            note As7
            note C8
            note As7
            note C8
    channel_end
Music_21_Channel_3:
      inst 26
      vol 11
      setRelease 1
      vibrato 44
            noteL Cs4, 3
            note Ds4
            note Cs4
            note Ds4
            note Cs4
            note Ds4
            note Cs4
            note Ds4
            note E4
            note Fs4
            note E4
            note Fs4
            note E4
            note Fs4
            note E4
            note Fs4
            note G4
            note A4
            note G4
            note A4
            note G4
            note A4
            note G4
            note A4
            note As4
            note C5
            note As4
            note C5
            note As4
            note C5
            note As4
            note C5
            note Cs5
            note Ds5
            note Cs5
            note Ds5
            note Cs5
            note Ds5
            note Cs5
            note Ds5
            note E5
            note Fs5
            note E5
            note Fs5
            note E5
            note Fs5
            note E5
            note Fs5
            note G5
            note A5
            note G5
            note A5
            note G5
            note A5
            note G5
            note A5
            note As5
            note C6
            note As5
            note C6
            note As5
            note C6
            note As5
            note C6
            note G5
            note A5
            note G5
            note A5
            note G5
            note A5
            note G5
            note A5
            note As5
            note C6
            note As5
            note C6
            note As5
            note C6
            note As5
            note C6
            note Cs6
            note Ds6
            note Cs6
            note Ds6
            note Cs6
            note Ds6
            note Cs6
            note Ds6
            note E6
            note Fs6
            note E6
            note Fs6
            note E6
            note Fs6
            note E6
            note Fs6
            note G6
            note A6
            note G6
            note A6
            note G6
            note A6
            note G6
            note A6
            note As6
            note C7
            note As6
            note C7
            note As6
            note C7
            note As6
            note C7
            note Cs7
            note Ds7
            note Cs7
            note Ds7
            note Cs7
            note Ds7
            note Cs7
            note Ds7
            note E7
            note Fs7
            note E7
            note Fs7
            note E7
            note Fs7
            note E7
            note Fs7
            note G7
            note A7
            note G7
            note A7
            note G7
            note A7
            note G7
            note A7
            note G7
            note A7
            note G7
            note A7
            note G7
            note A7
            note G7
            note A7
            note G7
            note A7
            note G7
            note A7
            note G7
            note A7
            note G7
            note A7
            note G7
            note A7
            note G7
            note A7
            note G7
            note A7
            note G7
            note A7
    channel_end
Music_21_Channel_4:
      inst 30
      vol 13
      setRelease 1
      vibrato 44
            noteL E2, 192
            note E2
            noteL E2, 96
    channel_end
Music_21_Channel_5:
            waitL 96
            wait
            wait
            wait
            sample 1
    channel_end
Music_21_Channel_6:
      psgInst 06ch
      setRelease 0
      vibrato 76
            psgNoteL E5, 2
            psgNote Fs5
            psgNote Gs5
            psgNote As5
            psgNote B5
            psgNote Cs6
            psgNote As5
            psgNote B5
            psgNote Cs6
            psgNote Ds6
            psgNote F6
            psgNote G6
            waitL 72
            waitL 60
            psgNoteL As5, 2
            psgNote B5
            psgNote Cs6
            psgNote Ds6
            psgNote F6
            psgNote G6
            waitL 24
            psgNoteL E5, 2
            psgNote Fs5
            psgNote Gs5
            psgNote As5
            psgNote B5
            psgNote Cs6
            psgNote As5
            psgNote B5
            psgNote Cs6
            psgNote Ds6
            psgNote F6
            psgNote G6
            waitL 72
            waitL 60
            psgNoteL As5, 2
            psgNote B5
            psgNote Cs6
            psgNote Ds6
            psgNote F6
            psgNote G6
            psgNote E5
            psgNote Fs5
            psgNote Gs5
            psgNote As5
            psgNote B5
            psgNote Cs6
            psgNote As5
            psgNote B5
            psgNote Cs6
            psgNote Ds6
            psgNote F6
            psgNote G6
            waitL 12
            psgNoteL E5, 2
            psgNote Fs5
            psgNote Gs5
            psgNote As5
            psgNote B5
            psgNote Cs6
            psgNote As5
            psgNote B5
            psgNote Cs6
            psgNote Ds6
            psgNote F6
            psgNote G6
            waitL 60
    channel_end
Music_21_Channel_7:
      psgInst 00h
      setRelease 0
      vibrato 76
            waitL 48
      psgInst 06ch
            psgNoteL E5, 2
            psgNote Fs5
            psgNote Gs5
            psgNote As5
            psgNote B5
            psgNote Cs6
            psgNote As5
            psgNote B5
            psgNote Cs6
            psgNote Ds6
            psgNote F6
            psgNote G6
            waitL 24
            waitL 12
            psgNoteL As5, 2
            psgNote B5
            psgNote Cs6
            psgNote Ds6
            psgNote F6
            psgNote G6
            waitL 36
            psgNoteL E5, 2
            psgNote Fs5
            psgNote Gs5
            psgNote As5
            psgNote B5
            psgNote Cs6
            psgNote As5
            psgNote B5
            psgNote Cs6
            psgNote Ds6
            psgNote F6
            psgNote G6
            waitL 12
            waitL 48
            psgNoteL E5, 2
            psgNote Fs5
            psgNote Gs5
            psgNote As5
            psgNote B5
            psgNote Cs6
            psgNote As5
            psgNote B5
            psgNote Cs6
            psgNote Ds6
            psgNote F6
            psgNote G6
            waitL 24
            waitL 12
            psgNoteL As5, 2
            psgNote B5
            psgNote Cs6
            psgNote Ds6
            psgNote F6
            psgNote G6
            waitL 36
            psgNoteL E5, 2
            psgNote Fs5
            psgNote Gs5
            psgNote As5
            psgNote B5
            psgNote Cs6
            psgNote As5
            psgNote B5
            psgNote Cs6
            psgNote Ds6
            psgNote F6
            psgNote G6
            waitL 12
      psgInst 0fh
            waitL 24
            psgNoteL D2, 6
            wait
            psgNote Cs2
            wait
            psgNote B1
            wait
            psgNoteL As1, 36
    channel_end
Music_21_Channel_8:
    channel_end